version: '3'

services:
#  traefik:
#    image: traefik
#    command: --api --docker
#    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
#      - "8090:8080"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - :/etc/traefik.toml
#      - :/acme.json
#    labels:
#      - "traefik.frontend.rule=Host:traefik"
#    networks:
#      - traefik

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    environment:
      - TZ=America/Detroit
      - PGID=${GROUP_ID}
      - PUID=${USER_ID}
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - ${MEDIA}:/downloads
      - ${MEDIA}:/watch
      - transmission_config:/config

  couchpotato:
    depends_on:
       - transmission
    image: linuxserver/couchpotato
    container_name: couchpotato
    restart: unless-stopped
    environment:
      - PGID=${GROUP_ID}
      - PUID=${USER_ID}
      - TZ=America/Detroit
      - UMASK_SET=022
    volumes:
      - ${COUCHCONFIG}:/config
      - ${MEDIA}:/downloads
      - ${MEDIA}:/movies
    ports:
      - "5050:5050"

  sickrage:
    depends_on:
      - transmission
    image: linuxserver/sickrage
    container_name: sickrage
    restart: unless-stopped
    environment:
      - PGID=${GROUP_ID}
      - PUID=${USER_ID}
      - TZ=America/Detroit
    volumes:
      - sickrage_config:/config
      - ${MEDIA}:/downloads
      - ${MEDIA}:/tv
    ports:
      - "8081:8081"

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: always
    network_mode: host
#    ports:
#      - "32400:32400"
#      - "1900:1900/udp"
#      - "3005:3005"
#      - "5353:5353/udp"
#      - "8324:8324"
#      - "32410:32410/udp"
#      - "32412:32412/udp"
#      - "32413:32413/udp"
#      - "32414:32414/udp"
    environment:
      - PLEX_UID=${USER_ID}
      - PLEX_GID=${GROUP_ID}
      - TZ="America/Detroit"
      - PLEX_CLAIM=claim-R9TehGcmVpUpqjQDySz9
      - ADVERTISE_IP="http://192.168.1.66:32400"
      - VERSION=docker
    volumes:
      - plex_config:/config
      - ${MEDIA}:/data
      - ${TEMP}:/transcode

volumes:
    couchpotato_config:
    transmission_config:
    sickrage_config:
    plex_config:

networks:
  traefik:
    external: true
